grandCentral/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns=[
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/signup', views.signup, name='signup'),

    path('menu/food/', views.FoodMenuItemList.as_view(), name='food_menu'),
    path('menu/food/create/', views.FoodMenuItemCreate.as_view(), name='food_menu_item_create'),
    path('menu/food/<int:pk>/', views.FoodMenuItemDetail.as_view(), name='food_menu_item_detail'),
    path('menu/food/<int:pk>/add_to_order', views.add_food_line_item, name='add_food_line_item'),
    path('menu/food/<int:foodmenuitem_id>/add_food_photo/', views.add_food_photo, name='add_food_photo'),
    path('menu/food/<int:pk>/update/', views.FoodMenuItemUpdate.as_view(), name='food_menu_item_update'),
    path('menu/food/<int:pk>/delete/', views.FoodMenuItemDelete.as_view(), name='food_menu_item_delete'),

    path('menu/drinks/', views.DrinkMenuItemList.as_view(), name='drink_menu'),
    path('menu/drinks/create/', views.DrinkMenuItemCreate.as_view(), name='drink_menu_item_create'),
    path('menu/drinks/<int:pk>/', views.DrinkMenuItemDetail.as_view(), name='drink_menu_item_detail'),
    path('menu/drinks/<int:pk>/add_to_order', views.add_drink_line_item, name='add_drink_line_item'),
    path('menu/drinks/<int:drinkmenuitem_id>/add_drink_photo/', views.add_drink_photo, name='add_drink_photo'),
    path('menu/drinks/<int:pk>/update/', views.DrinkMenuItemUpdate.as_view(), name='drink_menu_item_update'),
    path('menu/drinks/<int:pk>/delete/', views.DrinkMenuItemDelete.as_view(), name='drink_menu_item_delete'),

    path('menu/order/create', views.create_order, name='order_create'),
    path('menu/order/view', views.view_order, name='order_view'),
    path('menu/order/<int:order_id>/remove_item/<int:item_id>/', views.remove_item_from_order, name='remove_item_from_order'),

    path('event/', views.EventList.as_view(), name='event_list'),
    path('event/add_event', views.EventCreate.as_view(), name='event_create'),
    path('event/<int:pk>/', views.EventDetail.as_view(), name='event_detail'),
    path('event/<int:event_id>/add_event_photo/', views.add_event_photo, name='add_event_photo')
]

main_app/models.py
from django.db import models
from django.forms import FloatField, BooleanField, DecimalField
from django.urls import reverse
from django_quill.fields import QuillField
from datetime import date
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

PICKUP_DELIVER = (
    ('P', 'Pick up'),
    ('D', 'Delivery')
)
    
class SideOption(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
class AddedOption(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(default = 0.0, decimal_places = 2, max_digits = 10)

    def __str__(self):
        return f'{self.name} - ${self.price}'
    
class SizeOption(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(default = 0.0, decimal_places = 2, max_digits = 10)

    def __str__(self):
        return f'{self.name} - ${self.price}'

class GravyOption(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(default = 0.0, decimal_places = 2, max_digits = 10)

    def __str__(self):
        return f'{self.name} - ${self.price}'

class CookOption(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name    
    
class SauceOption(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class RemoveOption(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name  
    
class CoffeeSizeOption(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(default = 0.0, decimal_places = 2, max_digits = 10)

    def __str__(self):
        return f'{self.name} - ${self.price}'
    
class MilkOption(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(default = 0.0, decimal_places = 2, max_digits = 10)

    def __str__(self):
        return f'{self.name} - ${self.price}'
    
class CoffeeStrengthOption(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class SoftDrinkSizeOption(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(default = 0.0, decimal_places = 2, max_digits = 10)

    def __str__(self):
        return f'{self.name} - ${self.price}'

class HotChocolateOption(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
class FoodMenuItem(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    price = models.DecimalField(default = 1.0, decimal_places = 2, max_digits = 10)
    inStock = models.BooleanField(default = True)    
    side_option = models.ManyToManyField(SideOption, help_text='Select all that apply', blank=True)
    added_option = models.ManyToManyField(AddedOption, help_text='Select all that apply', blank=True)
    size_option = models.ManyToManyField(SizeOption, help_text='Select all that apply', blank=True)
    gravy_option = models.ManyToManyField(GravyOption, help_text='Select all that apply', blank=True)
    cook_option = models.ManyToManyField(CookOption, help_text='Select all that apply', blank=True)
    sauce_option = models.ManyToManyField(SauceOption, help_text='Select all that apply', blank=True)
    remove_option = models.ManyToManyField(RemoveOption, help_text='Select all that apply', blank=True)

    def __str__(self):
        return self.name
            
    def size_calculation(self):
        result = []
        for size in self.size_option.all():
            total_price = self.price + size.price
            result.append({'name': size.name, 'price': total_price})
        print(result)
        return result
            
    def get_absolute_url(self):
        return reverse('food_menu_item_detail', kwargs={'pk': self.id})
    
class DrinkMenuItem(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    price = models.DecimalField(default = 1.0, decimal_places = 2, max_digits = 10)
    inStock = models.BooleanField(default = True)
    inhouse_option = models.BooleanField(default = False)
    coffee_size_option = models.ManyToManyField(CoffeeSizeOption, help_text='Select all that apply', blank=True)
    milk_option = models.ManyToManyField(MilkOption, help_text='Select all that apply', blank=True)
    coffee_strength_option = models.ManyToManyField(CoffeeStrengthOption, help_text='Select all that apply', blank=True)
    soft_drink_size_option = models.ManyToManyField(SoftDrinkSizeOption, help_text='Select all that apply', blank=True)
    hot_chocolate_option = models.ManyToManyField(HotChocolateOption, help_text='Select all that apply', blank=True)
    
    def __str__(self):
        return self.name
            
    def coffee_size_calculation(self):
        result = []
        for size in self.coffee_size_option.all():
            total_price = self.price + size.price
            result.append({'name': size.name, 'price': total_price})
        print(result)
        return result
    
    def soft_drink_size_calculation(self):
        result = []
        for size in self.soft_drink_size_option.all():
            total_price = self.price + size.price
            result.append({'name': size.name, 'price': total_price})
        print(result)
        return result
    
    def get_absolute_url(self):
        return reverse('drink_menu_item_detail', kwargs={'pk': self.id})
    
class Order(models.Model):
    name = models.CharField(max_length = 50, help_text='Enter a name for the order', default="")
    pickup_deliver = models.CharField(
        max_length=1,
        choices=PICKUP_DELIVER,
        default=PICKUP_DELIVER[0][0]
    )
    date = models.DateField()
    total_price = models.FloatField(default = 0.0)
    notes = models.TextField(max_length=500, default='')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    isInProgress = models.BooleanField(default=True)

    def __str__(self):
        return f'Order no. {self.id}'
    
    class Meta:
        ordering = ['-date']

    def save(self, *args, **kwargs):
        if not self.id:
            self.date = date.today()
            super().save(*args, **kwargs)

class LineItem(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField(default = 0)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    side_option = models.ManyToManyField(SideOption, help_text='Select all that apply', blank=True)
    added_option = models.ManyToManyField(AddedOption, help_text='Select all that apply', blank=True)
    size_option = models.ManyToManyField(SizeOption, help_text='Select all that apply', blank=True)
    gravy_option = models.ManyToManyField(GravyOption, help_text='Select all that apply', blank=True)
    cook_option = models.ManyToManyField(CookOption, help_text='Select all that apply', blank=True)
    sauce_option = models.ManyToManyField(SauceOption, help_text='Select all that apply', blank=True)
    remove_option = models.ManyToManyField(RemoveOption, help_text='Select all that apply', blank=True)
    coffee_size_option = models.ManyToManyField(CoffeeSizeOption, help_text='Select all that apply', blank=True)
    milk_option = models.ManyToManyField(MilkOption, help_text='Select all that apply', blank=True)
    coffee_strength_option = models.ManyToManyField(CoffeeStrengthOption, help_text='Select all that apply', blank=True)
    soft_drink_size_option = models.ManyToManyField(SoftDrinkSizeOption, help_text='Select all that apply', blank=True)
    hot_chocolate_option = models.ManyToManyField(HotChocolateOption, help_text='Select all that apply', blank=True)
   
    # def total_price(self):
    #     total_price = 0
    #     for item_price in self.price.all():
    #         total_price += item_price
    #     print(total_price)
    #     return total_price

    def __str__(self):
        return f'Item {self.name} - {self.order}'
 
class MenuOption(models.Model):
    category = models.CharField(max_length=50)
    item = models.ManyToManyField(FoodMenuItem)

    def __str__(self):
        return self.category

class DietaryOption(models.Model):
    type = models.CharField(max_length=50)
    item = models.ManyToManyField(FoodMenuItem)

    def __str__(self):
        return self.type
    
class FoodPhoto(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=200)
    food = models.ForeignKey(FoodMenuItem, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo of {self.name}"
    
class DrinkPhoto(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=200)
    drink = models.ForeignKey(DrinkMenuItem, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo of {self.name}"
    
class Event(models.Model):
    name = models.CharField(max_length=100)
    description = QuillField(default='')

    def __str__(self):
        return f"Event: {self.name}"
    
    def get_absolute_url(self):
        return reverse('event_detail', kwargs={'pk': self.id})

class EventPhoto(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=200)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo of {self.name}"

class VenuePhoto(models.Model):
    name = models.CharField(max_length=50)
    url = models.CharField(max_length=200)

    def __str__(self):
        return f"Photo of {self.name}"
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    marketing = models.BooleanField(default=False)
    phone = models.IntegerField(default=0)
    street_address = models.CharField(max_length = 50, blank=True)

main_app/forms.py
from django import forms
from .models import LineItem, Order, Profile
from django.forms import EmailField 
from django.forms.models import inlineformset_factory
from django.utils.translation import gettext_lazy as _ 
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
    
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("phone", "street_address", "suburb", "postcode")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['street_address'].required = False
    def clean(self):
        cleaned_data = super().clean()
        pickup_deliver = cleaned_data.get('pickup_deliver')

        if pickup_deliver == 'P':
            self.fields['street_address'].required = False
        elif pickup_deliver == 'D':
            self.fields['street_address'].required = True

        return cleaned_data
    
class LineItemForm(forms.ModelForm):
    class Meta:
        model = LineItem
        fields = (
            "name", 
            "price", 
            "order", 
            "side_option",
            "added_option",
            "size_option",
            "gravy_option",
            "cook_option",
            "sauce_option",
            "remove_option"
        )

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ("name", "pickup_deliver")

main_app/templates/addlineitem.html
{% extends 'base.html' %}
{% block content %}

{% if error_message %}
    <p>{{ error_message }}</p>
{% endif %}



<div class="container m-5">
    <form method="post">
        {% csrf_token %}
        <div>
            <label class ="visually-hidden-focusable" for="id_name">Name:</label>
            <input class ="visually-hidden-focusable" name="name" id="id_name" value="{{item.name}}"><span class="fs-2 mb-2">{{ item.name }}</span></input>
        </div>
        <div>
            {% if item.foodphoto_set.exists %}
                {% for photo in item.foodphoto_set.all %}
                    <img src="{{ photo.url }}" class="img-fluid rounded-start" alt="Image of {{ food.name }}" style="max-width: 250px;">
                {% empty %}
                    <div></div>
                {% endfor %}
            {% endif %}
        </div>
        <div>
            {% if item.drinkphoto_set.exists %}
                {% for photo in item.drinkphoto_set.all %}
                    <img src="{{ photo.url }}" class="img-fluid rounded-start" alt="Image of {{ food.name }}" style="max-width: 250px;">
                {% empty %}
                    <div></div>
                {% endfor %}
            {% endif %}
        </div>
        <div>
            <label for="id_price">Price:</label>
        <input class="visually-hidden-focusable" name="price" id="id_price" value="{{ item.price }}"><span id="display_price">${{ item.price }}</span> </input>
        </div>
        <div>
            <label for="id_order">Your Order No. is</label>
            <input class="visually-hidden-focusable" name="order" id="id_order" value="{{ order.id }}"> {{ order.id }}</input>
        </div>
        <div>
            {% if item.side_option.exists %}
                <label for="id_side_option">Choose your side:</label>
                <select class="form-select" name="side_option" id="id_side_option" >
                    {% for option in item.side_option.all %}
                        <option value="{{ option.id }}">{{ option.name }}</option>
                    {% endfor %}
                </select>
            {% else %}
                <span></span>
            {% endif %}
        </div>
        <div>
            {% if item.added_option.exists %}
                <label for="id_added_option">Things to add:</label>
                <select class="form-select" name="added_option" id="id_added_option" multiple>
                    {% for option in item.added_option.all %}
                        <option value="{{ option.id }}" option-price="{{ option.price }}">
                            {{ option.name }} - Additional ${{ option.price }}
                        </option>
                    {% endfor %}
                </select>
                <div class="form-text">Ctrl + click to select more than one</div>
            {% else %}
                <span></span>
            {% endif %}
        </div>
        <div>
            {% if item.size_option.exists %}
                <label for="id_size_option">Which size?</label>
                <select class="form-select" name="size_option" id="id_size_option" >
                    {% for option in item.size_option.all %}
                        <option value="{{ option.id }}" option-price="{{ option.price }}">
                            {{ option.name }} - Additional ${{ option.price }}
                        </option>
                    {% endfor %}
                </select>
            {% else %}
                <span></span>
            {% endif %}
        </div>
        <div>
            {% if item.gravy_option.exists %}
                <label for="id_gravy_option">Choose gravy:</label>
                <select class="form-select" name="gravy_option" id="id_gravy_option" multiple>
                    {% for option in item.gravy_option.all %}
                        <option value="{{ option.id }}" option-price="{{ option.price }}">
                            {{ option.name }} - ${{ option.price }}
                        </option>
                    {% endfor %}
                </select>
                <div class="form-text">Ctrl + click to select more than one:</div>
            {% else %}
                <span></span>
            {% endif %}
        </div>
        <div>
            {% if item.cook_option.exists %}
                <label for="id_cook_option">How would you like it cooked?</label>
                <select class="form-select" name="cook_option" id="id_cook_option" >
                    {% for option in item.cook_option.all %}
                        <option value="{{ option.id }}">{{ option.name }}</option>
                    {% endfor %}
                </select>
            {% else %}
                <span></span>
            {% endif %}
        </div>
        <div>
            {% if item.sauce_option.exists %}
                <label for="id_sauce_option">Choose sauce:</label>
                <select class="form-select" name="sauce_option" id="id_sauce_option" >
                    {% for option in item.sauce_option.all %}
                        <option value="{{ option.id }}">{{ option.name }}</option>
                    {% endfor %}
                </select>
            {% else %}
                <span></span>
            {% endif %}
        </div>
        <div>
            {% if item.remove_option.exists %}
                <label for="id_remove_option">Would you like anything removed?</label>
                <select class="form-select" name="remove_option" id="id_remove_option" multiple>
                    {% for option in item.remove_option.all %}
                        <option value="{{ option.id }}">{{ option.name }}</option>
                    {% endfor %}
                </select>
                <div class="form-text">Ctrl + click to select more than one:</div>
            {% else %}
                <span></span>
            {% endif %}
        </div>
        <div>
            {% if item.coffee_size_option.exists %}
                <label for="id_coffee_size_option">Choose size:</label>
                <select class="form-select" name="coffee_size_option" id="id_coffee_size_option" >
                    {% for option in item.coffee_size_option.all %}
                        <option value="{{ option.id }}" option-price="{{ option.price }}">
                            {{ option.name }} - Additional ${{ option.price }}
                        </option>
                    {% endfor %}
                </select>
            {% else %}
                <span></span>
            {% endif %}
        </div>
        <div>
            {% if item.milk_option.exists %}
                <label for="id_milk_option">Choose milk:</label>
                <select class="form-select" name="milk_option" id="id_milk_option" >
                    {% for option in item.milk_option.all %}
                        <option value="{{ option.id }}" option-price="{{ option.price }}">
                            {{ option.name }} - Additional ${{ option.price }}
                        </option>
                    {% endfor %}
                </select>
            {% else %}
                <span></span>
            {% endif %}
        </div>
        <div>
            {% if item.coffee_strength_option.exists %}
                <label for="id_coffee_strength_option">Choose strength:</label>
                <select class="form-select" name="coffee_strength_option" id="id_coffee_strength_option" >
                    {% for option in item.coffee_strength_option.all %}
                        <option value="{{ option.id }}">{{ option.name }}</option>
                    {% endfor %}
                </select>
            {% else %}
                <span></span>
            {% endif %}
        </div>
        <div>
            {% if item.soft_drink_size_option.exists %}
                <label for="id_soft_drink_size_option">Choose size:</label>
                <select class="form-select" name="soft_drink_size_option" id="id_soft_drink_size_option" >
                    {% for option in item.soft_drink_size_option.all %}
                        <option value="{{ option.id }}" option-price="{{ option.price }}">
                            {{ option.name }} - Additional ${{ option.price }}
                        </option>
                    {% endfor %}
                </select>
            {% else %}
                <span></span>
            {% endif %}
        </div>
        <div>
            {% if item.hot_chocolate_option.exists %}
                <label for="id_hot_chocolate_option">Choose flavor:</label>
                <select class="form-select" name="hot_chocolate_option" id="id_hot_chocolate_option" >
                    {% for option in item.hot_chocolate_option.all %}
                        <option value="{{ option.id }}">{{ option.name }}</option>
                    {% endfor %}
                </select>
            {% else %}
                <span></span>
            {% endif %}
        </div>
        <input type="submit" value="Submit" class="btn btn-dark">
    </form>
</div>


{% block javascript  %}
    <script>
        function getElementIfExists(id){
            const element = document.getElementById(id);
            return element ? element : null;
        };

        const foodSizeOptionSelect = getElementIfExists('id_size_option');
        const gravyOptionSelect = getElementIfExists('id_gravy_option');
        const addedOptionSelect = getElementIfExists('id_added_option');
        const coffeeSizeOptionSelect = getElementIfExists('id_coffee_size_option');
        const milkOptionSelect = getElementIfExists('id_milk_option');
        const softDrinkSizeOptionSelect = getElementIfExists('id_soft_drink_size_option');

        const displayPrice = document.getElementById('display_price');
        const originalPrice = parseFloat(document.getElementById('id_price').value);
        const priceInput = document.getElementById('id_price');

        foodSizeOptionSelect?.addEventListener('change', updateTotal);
        gravyOptionSelect?.addEventListener('change', updateTotal);
        addedOptionSelect?.addEventListener('change', updateTotal);
        coffeeSizeOptionSelect?.addEventListener('change', updateTotal);
        milkOptionSelect?.addEventListener('change', updateTotal);
        softDrinkSizeOptionSelect?.addEventListener('change', updateTotal);

        let runningTotal = originalPrice;

        function updateTotal(){
            runningTotal = originalPrice;

            const selectedSize = parseFloat(foodSizeOptionSelect?.options[foodSizeOptionSelect.selectedIndex]?.getAttribute('option-price')) || 0;
            runningTotal += selectedSize

            const selectedCoffeeSize = parseFloat(coffeeSizeOptionSelect?.options[coffeeSizeOptionSelect.selectedIndex]?.getAttribute('option-price')) || 0;
            runningTotal += selectedCoffeeSize

            const selectedMilk = parseFloat(milkOptionSelect?.options[milkOptionSelect.selectedIndex]?.getAttribute('option-price')) || 0;
            runningTotal += selectedMilk

            const selectedSoftDrinkSize = parseFloat(softDrinkSizeOptionSelect?.options[softDrinkSizeOptionSelect.selectedIndex]?.getAttribute('option-price')) || 0;
            runningTotal += selectedSoftDrinkSize

            if (gravyOptionSelect && gravyOptionSelect.selectedOptions){
                for (const option of gravyOptionSelect.selectedOptions){
                    const gravyPrice = parseFloat(option.getAttribute('option-price'));
                    runningTotal += gravyPrice
                }
            }
            
            if (addedOptionSelect && addedOptionSelect.selectedOptions){
                for (const option of addedOptionSelect?.selectedOptions){
                    const addedPrice = parseFloat(option.getAttribute('option-price'));
                    runningTotal += addedPrice
                }
            }
            updateRunningTotal(runningTotal)
        }

        function updateRunningTotal(total){
            displayPrice.innerText = `$${total.toFixed(2)}`;
            priceInput.value = parseFloat(total.toFixed(2));
        }
        
    </script>
{% endblock %}

{% endblock %}

main_app/templates/create_order.html
{% extends 'base.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <div>
        <label for="id_name" class="form-label" >Name:</label>
        <div class="helptext">Enter a name for the order</div>
        <input type="text" name="name" maxlength="50" required id="id_name">
    </div>
    <div>
        <label for="id_pickup_deliver" class="form-label" >Pickup deliver:</label>
        {{ order_form.pickup_deliver }}
    </div>
    <div>
        <label for="id_phone" class="form-label" >Phone:</label>
        {{ profile_form.phone }}
    </div>
    <div id="address_field">
        <div>
            <label for="id_street_address" class="form-label" >Street address:</label>
            {{ profile_form.street_address }}
        </div>
        <div>
            <label for="id_suburb" class="form-label" >Suburb:</label>
            {{ profile_form.suburb }}
        </div>
        <div>
            <label for="id_postcode" class="form-label" >Postcode:</label>
            {{ profile_form.postcode }}
        </div>
    </div>
    <button class="btn btn-dark" type="submit">Save changes</button>
</form>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const pickupDeliverDropdown = document.getElementById("id_pickup_deliver");
    const addressTextarea = document.getElementById("address_field");

    pickupDeliverDropdown.addEventListener("change", function () {
        addressTextarea.style.display = this.value === "D" ? "block" : "none";
    });

    addressTextarea.style.display = pickupDeliverDropdown.value === "D" ? "block" : "none";
});
</script>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-10">
            <div id="carouselExampleIndicators" class="carousel slide">
                <div class="carousel-indicators">
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                </div>
                <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="https://grandcentralhotel.s3.ap-southeast-2.amazonaws.com/exterior_trees.png" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="https://grandcentralhotel.s3.ap-southeast-2.amazonaws.com/outisde_1.png" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="https://grandcentralhotel.s3.ap-southeast-2.amazonaws.com/cafe.png" class="d-block w-100" alt="...">
                </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
    </div>
</div>


<div class="container m-6">
    <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for event in event_list %}
            <div class="col">
                <div class="card text-center h-100 m-3" style="max-width: 300px">
                    {% for photo in event.eventphoto_set.all %}
                        <img class="card-img-left m-2" style='max-height: 300px' src="{{photo.url}}">
                    {% empty %}
                        <div class="card-panel center-align">No Photos Uploaded</div>
                    {% endfor %}
                        <div class="card-body">
                        <h5 class="card-title">{{ event.name }}</h5>
                        <p class="card-text">{{ event.description.html|safe }}</p>
                        {% if user.is_superuser %}
                            <a href="{% url 'event_detail' event.id %}">Edit</a>
                        {% endif %}
                        </div>
                </div>
            </div>
            {% endfor %}
    </div>
</div>

{% endblock %}